# Generated by Django 4.2.7 on 2024-01-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id_info', models.AutoField(primary_key=True, serialize=False)),
                ('primeira', models.IntegerField()),
                ('segunda', models.IntegerField()),
            ],
        ),
    ]
