# Generated by Django 4.2.7 on 2024-01-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Corte',
        ),
        migrations.RenameField(
            model_name='corte',
            old_name='id_info',
            new_name='id_corte',
        ),
    ]
