# Generated by Django 4.2.7 on 2024-01-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.CharField(max_length=40)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
    ]
