# Generated by Django 5.0.2 on 2024-03-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('answer_1', models.CharField(max_length=255)),
                ('answer_2', models.CharField(max_length=255)),
                ('correct', models.CharField(choices=[('answer_1', 'Answer_1'), ('answer_2', 'Answer_2'), ('answer_3', 'Answer_3'), ('answer_4', 'Answer_4'), ('answer_5', 'Answer_5')], max_length=8)),
            ],
        ),
    ]
