# Generated by Django 5.0.2 on 2024-03-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_3',
            field=models.CharField(default='SOME_STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_4',
            field=models.CharField(default='SOME_STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_5',
            field=models.CharField(default='SOME_STRING', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.CharField(default='SOME_STRING', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.CharField(default='SOME_STRING', max_length=255),
        ),
    ]
