# Generated by Django 5.0.2 on 2024-03-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_question_answer_3_question_answer_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.CharField(default='a)', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.CharField(default='b)', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_3',
            field=models.CharField(default='c)', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_4',
            field=models.CharField(default='d)', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_5',
            field=models.CharField(default='e)', max_length=255),
        ),
    ]
