# Generated by Django 5.0.2 on 2024-03-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_question_answer_1_alter_question_answer_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(choices=[('answer_1', 'a)'), ('answer_2', 'b)'), ('answer_3', 'c)'), ('answer_4', 'd)'), ('answer_5', 'e)')], max_length=8),
        ),
    ]
