# Generated by Django 5.0.2 on 2024-03-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_question_answer_1_remove_question_answer_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.IntegerField(default=''),
        ),
    ]
