# Generated by Django 5.0.2 on 2024-03-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_question_content_question_test_question_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.TextField(default=''),
        ),
    ]
