# Generated by Django 5.0.2 on 2024-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_question_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.TextField(),
        ),
    ]
