# Generated by Django 5.0.2 on 2024-03-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_question_content_alter_question_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='year',
            new_name='ano',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(choices=[('A', 'A)'), ('B', 'B)'), ('C', 'C)'), ('D', 'D)'), ('E', 'E)')], max_length=2),
        ),
    ]
